# Generated by Django 6.1.1 on 2026-09-27 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('in_progress', 'In progress'), ('deployed', 'Deployed'), ('archived', 'Archived')], db_index=True, default='concept', max_length=16)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(max_length=240)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio_projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency_note', models.CharField(blank=True, max_length=160)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_links', to='portfolio_projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_links', to='portfolio_technologies.technology')),
            ],
            options={
                'ordering': ['project__order', 'technology__name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', through='portfolio_projects.ProjectTechnology', to='portfolio_technologies.technology'),
        ),
        migrations.AddConstraint(
            model_name='projecttechnology',
            constraint=models.UniqueConstraint(fields=('project', 'technology'), name='unique_project_technology'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured', 'status'], name='project_featured_status_idx'),
        ),
    ]
