# Generated by Django 6.1.1 on 2026-09-27 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('issuer', models.CharField(max_length=180)),
                ('credential_id', models.CharField(blank=True, max_length=160)),
                ('credential_url', models.URLField(blank=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-issued_on', 'order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('issued_on__isnull', True), ('expires_on__gte', models.F('issued_on')), _connector='OR'), name='cert_expiry_after_issue')],
            },
        ),
    ]
