# Generated by Django 6.1.1 on 2026-09-27 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('problem', models.TextField(blank=True)),
                ('proposed_solution', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('in_development', 'In development'), ('deployed', 'Deployed')], db_index=True, default='concept', max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
