# Generated by Django 6.1.1 on 2026-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupidea',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='startupidea',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
