# Generated by Django 6.1.1 on 2026-09-27 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=160)),
                ('organization', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('organization_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
                'indexes': [models.Index(fields=['-start_date'], name='experience_start_desc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_end_after_start'), models.CheckConstraint(condition=models.Q(('end_date__isnull', False), ('is_current', True), _negated=True), name='current_experience_without_end')],
            },
        ),
    ]
