# Generated by Django 6.1.1 on 2026-09-27 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=180)),
                ('qualification', models.CharField(max_length=180)),
                ('field_of_study', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-end_date', '-start_date', 'order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='education_end_after_start'), models.CheckConstraint(condition=models.Q(('end_date__isnull', False), ('is_current', True), _negated=True), name='current_education_without_end')],
            },
        ),
    ]
