# Generated by Django 6.1.1 on 2026-09-27 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('cloud', 'Cloud'), ('tooling', 'Tooling'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('icon_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
